### ISSUE TITLE
[SPIKE] Explore JSON/HTTP vs. protobuf/GRPC for communication between nodes

### ISSUE THREAD

**Issue by eysk-io** [CPSC416-Project/issue-tracking#18]

**Comment by derekcswong** [comment]
I used the json/encoding library to encode and decode the CRDT struct we will pass around nodes. Right now we send and receive data (in the form of a CRDTStruct) through the stream which should do the trick for our requirements. Progress pushed to the p2p branch.

https://github.com/416-MemoryLane/MemoryLane/blob/37eb5702677b32030d3cce7700c7804429f3947a/app.go#L147-L169

**Comment by eysk-io** [comment]
Since we already have an implementation using JSON for Wingman (as per https://github.com/416-MemoryLane/issue-tracking/issues/18#issuecomment-1483622568), serialization/deserialization of JSON is trivial from the perspective of our JavaScript client, and the additional performance improvements are not required or worth the additional development time, we will use JSON.
