### ISSUE TITLE
Adjust album deletion behaviour in Galactus

### ISSUE THREAD

**Issue by eysk-io** [CPSC416-Project/issue-tracking#24]
When a user deletes an album via the ui, she/he is not actually deleting the album. Instead, she/he is only leaving the album. This behaviour should be reflected in Galactus . Only when it's the last member of the album that deletes the album, the album is cleared in the db.

**Comment by scott-m-king** [comment]
Changed `delete_album` endpoint to `leave_album` and updated API docs
